### ISSUE TITLE
Not able to view the full response

### ISSUE THREAD

**Issue by snaggen** [LucasPickering/slumber#111]
The response view is a bit limited. I had a response that was a json as one long line, but I couldn't view the end of that line. 
So, I suggest the following simple alternatives, 
1. Key bindings to scroll to the end of the line
2. Toggle line wrapping on/off
3. Possible to reformat well known formats like json

**Comment by LucasPickering** [comment]
1. Yes the lack of horizontal scrolling is something I've been punting on for a while. Horizontal scrolling is slightly annoying because left/right arrow are already used to change tabs. 
2. Line wrapping would work but is slightly complicated to implement so again, I've been punting.
3. It actually will automatically reformat JSON, but only if it recognizes it as JSON via the `Content-Type` header of the response. If it's not happening in your case, that means the `Content-Type` header has something other than `application/json`. Could you post the value of that header from your response? it's possible this is #103

**Comment by snaggen** [comment]
Yes, an extended json is used for the response.

**Comment by LucasPickering** [comment]
Horizontal scrolling is possible now (pending the next release). I'm not going to implement line wrapping yet, because it's a lot more complicated. Ratatui supports it, but then the line numbers get completely messed up. I'm hoping horizontal scrolling is enough for now.
