### ISSUE TITLE
Insomnia migration improvements

### ISSUE THREAD

**Issue by LucasPickering** [LucasPickering/slumber#12]
The insomnia migration tool is half-baked, some things that need to be improved:

- Support chained values
- Handle base environment to merge into others
  - Ideally this would be written as an anchor in the yaml, idk if serde_yaml supports that

Other stuff too, add to this list as necessary

**Comment by LucasPickering** [comment]
> Seems really far away from ever working, it literally doesn't even know how to parse Basic auth. I suspect it needs to be more dynamically typed and be able to just convert things it understands and skip the rest, while defaulting missing required fields

@pkaminsky This is a pretty condescending and unhelpful comment, especially for a feature that's very clearly marked as experimental. In the future if you'd like to submit a bug report, please include information such as the Insomnia collection being converted and the error message(s) you received.

**Comment by pkaminsky** [comment]
It's not unhelpful, I gave my suggestions, which I still think are right. I looked up the code for the error message I was getting and it explicitly explodes if the auth type is not Bearer. My suggestion, stated more verbosely, is that it's probably unlikely the tool can ever be comprehensive and flawless, so instead it should just convert as much text as possible, without erroring out on things it can't parse, with the expectation that the end user has to go back and manually touch-up what's missing. Anything not convertible should be left blank, unless blank is an invalid value in Slumber yaml, in which case a sensible default can be applied. Currently the tool will error and not produce a file. Unfortunately I can't provide my Insomnia collection since it has private information.
