### ISSUE TITLE
feature request: Save Body As File

### ISSUE THREAD

**Issue by kristopherbullinger** [LucasPickering/slumber#183]
Motivation:
Users may benefit from being able to open non-human readable response bodies with other programs, such as an image viewer or database.
Users may benefit from being able to view human-readable response bodies in text editors with syntax highlighting and other modern features enabled.

Feature summary:
I propose adding an option on the Response Body panel which prompts the user to specify a file name, populated by default with the final segment of the request path, and saves the body into a file with that name upon confirmation by the user.

Proposed workflow:
1. user makes request to `https://myapi.com/cat.png`
2. body appears as byte sequence in the Response Body panel
3. user navigates to the Result Body panel, presses a button to initiate the "save locally" flow
4. a modal appears: "Save Body To File? Filename: `cat.png`"
5. the user may edit the filename
6. press ESC to cancel or Enter to save the file

Thank you for your consideration.

**Comment by LucasPickering** [comment]
I've started working on this, but due to the suboptimal architecture of the UI it's going to take a bit of work. Some considerations for behavior:

- Should it populate a default path in the text box? We could guess at the file name in a few ways:
  - `Content-Disposition` header
  - Fall back to guessing extension from `Content-Type` header, with some placeholder for the basename
  - Leave it empty for unknown content types
- If the path contains directories that don't yet exist, should it create them?
- What happens if the file already exists? Overwrite?
  - Ideally we'd show a prompt that asks if you want to overwrite. UI shouldn't be too tricky for that

If anyone has input please let me know
