### ISSUE TITLE
Allow editing of collections with `$EDITOR`, or a way to configure the same

### ISSUE THREAD

**Issue by apreifsteck** [LucasPickering/slumber#262]
**Did you [search](https://github.com/LucasPickering/slumber/issues) for existing issues already?**
Yes 👍 

**Is your feature request related to a problem? Please describe.**
When I take an `Action` to edit a collection, VSCode is opened to edit the file. While VSCode is installed on my machine and is my default application for editing most documents, I don't actually use it. I edit most any file in a terminal editor like Helix.

**Describe the solution you'd like**
Have the `Edit Collection` action open a buffer to edit the collection using the configured `$EDITOR`, or a way to configure this to occur

I also found [this reddit thread](https://www.reddit.com/r/HelixEditor/comments/12c1t2b/how_to_set_as_default_editor_in_macos/) about using Automator to open up a terminal and launch Helix for a file, but that's not really what I'm looking for either.

**Describe alternatives you've considered**
I could always just open up another terminal pane, so this is really more of a qol thing.

**Additional context**
broot has some [configuration options to this effect](https://github.com/Canop/broot/blob/0bd53450999e66ad60fbd218cf571d458d3b5174/website/docs/tricks.md?plain=1#L119).
broot is the best example of what I'm looking for, because when you close the `$EDITOR` buffer it takes you back to the broot tui. Git would be the second best example; when you're rebasing or editing a commit message or something like that.

As an aside, thank you very much for building this tool, it is fantastic!

**Comment by LucasPickering** [comment]
Thank you for the very detailed feature request :) It makes my job much easier. This is totally possible and it looks like gitui supports it (added in [this PR](https://github.com/extrawurst/gitui/pull/114/files)). I see two possible implementations for this:

- Always use the editor defined in `$VISUAL`/`$EDITOR`. This is simple and still allows users to use VSCode or another GUI editor by setting that env var
- Add a configuration flag like `visual_editor: true`. When enabled it will use the default editor for `.yml` files, but when disabled it will check `$VISUAL`/`$EDITOR`
  - Default value could go either way, I would learn toward `false` though because it's simpler

Both are equally feasible from a technical standpoint so it's entirely a usability question. My intuition is that Slumber users are generally going to be at least moderately comfortable in the terminal; it's unlikely someone is uncomfortable using a terminal editor but wants a terminal HTTP client. Additionally, we would simply be mirroring the behavior of git, and I would also guess that the vast majority of Slumber users are comfortable with the git CLI. I'm going to get started on implementation, and I'll think about this question a bit more.

**Comment by apreifsteck** [comment]
Thanks for taking a look!

I think your intuition is spot on. I don't have too much of a preference myself, but if you're having trouble picking a route to go with, I can give my two cents (for what it's worth)

- Using `$EDITOR` by default could lead to a more streamlined experience, since users won't have to wait for an app to load (maybe not a big deal if it's already open? Like I said, I never have mine open), and it could be less of a context switch (same window and all that), but it would be a change from the current default.
- Are your users cool with breaking backwards compatibility? I saw you have a Discord, maybe that's a place to talk more if you need guidance, or...
- What would you prefer? Seems to me that one of the big perks of being the project owner is that you can shape the project in whatever way you like best 😄

Regardless of what you end up deciding, it'll 100% work. Thanks again for getting started on this so quickly!

**Comment by LucasPickering** [comment]
@apreifsteck Thanks for pointing out the Discord link. I swear I set it to never expire but apparently not... I just made a new link if you want to try joining again.

**Comment by LucasPickering** [comment]
@apreifsteck Just released a beta version with this change in it, do you mind testing it out? I just want to make sure there's no bugs around handing the terminal off to vim or coming back. You can install with:

```
cargo install slumber --version 1.5.0-beta.1
```

**Comment by apreifsteck** [comment]
Thank you so much! It works great 👍
