### ISSUE TITLE
Implement .env chain source

### ISSUE THREAD

**Issue by gintsgints** [LucasPickering/slumber#265]
**Did you [search](https://github.com/LucasPickering/slumber/issues) for existing issues already?**
Yes

**Is your feature request related to a problem? Please describe.**
If I have multiple secrets, I have to put them each one file. Also if I want secrets used for different environments, more files should be created.

**Describe the solution you'd like**
There could be a chain which reads dynamic variables from .env file. And also as possibility from environment variables (for cli execution).

**Describe alternatives you've considered**
I can read values, one by one from file.

**Comment by LucasPickering** [comment]
I'm not sure I exactly understand the request, but you can already ready environment variables in a template via the `{{env.VARIABLE}}` key ([see docs](https://slumber.lucaspickering.me/book/api/request_collection/template.html#template-sources)). This is not very visible in the docs so that could probably be improved. Does that cover your request or are you asking for something else?

**Comment by gintsgints** [comment]
Thank you for info. That covers my request partly. Is it possible that environment variables got read from .env file too? Or does it reads it already?

**Comment by gintsgints** [comment]
Also there is little issue with password read without chain. It has no ability to set it as sensitive.

**Comment by LucasPickering** [comment]
It does not currently read `.env` file, and I'd prefer to keep it that way. My goal is to keep Slumber as focused as possible, and there are already other tools (e.g. `source`) that you can use to read `.env` before launching Slumber. That does have the downside of not reloading Slumber when the `.env` file changes. Here's a possible solution for you:

```yaml
chains:
  username:
    source: !command
      command: ["bash", "-c", "source .env; echo $USERNAME"]
    trim: both
  password:
    source: !command
      command: ["bash", "-c", "source .env; echo $PASSWORD"]
    sensitive: true
    trim: both
```

It is repetitive and clunky so I definitely agree there should be a better way to do this, but I'd like it to be more flexible than something specific to `.env` files. I'm going to think about possible solutions, and in the mean time I'll add a `!env` chain type for loading a single env variable, so you can mark env variables as `sensitive`. The `{{env.VARIABLE}}` syntax predates the `sensitive` field (and all other chain configuration), so it wasn't a consideration then and I haven't thought much about it since.

**Comment by LucasPickering** [comment]
`!env` chain source added in #266, it'll be in the next release

**Comment by gintsgints** [comment]
Thank you.
