### ISSUE TITLE
Actions in vim are sometimes captured by Slumber

### ISSUE THREAD

**Issue by LucasPickering** [LucasPickering/slumber#351]
**Did you [search](https://github.com/LucasPickering/slumber/issues) for existing issues already?**

Yep

**Describe the bug**
_A clear and concise description of what the bug is_

Sometimes when entering vim (e.g. to edit the collection file), some vim actions are picked up by Slumber. This means when you exit vim and get back to slumber, the UI state may be different because of hotkeys being hit. For example if you happened to type an "r" while in vim, it may have switched you to the request/response pane.

**To Reproduce**
_Steps to reproduce the behavior_

I haven't found a consistent reproduction. Sometimes it happens, sometimes it doesn't.

1. Edit Collection
2. Type some stuff into vim
3. Exit and go back to slumber
4. Check if UI state changed

**Expected behavior**
_A clear and concise description of what you expected to happen_

Actions don't get captured by Slumber

**Screenshots**
_If applicable, add screenshots to help explain your problem_

**Version (please complete the following information):**

- OS: Macos 14.6.1
- Terminal: iTerm 3.5.3
- Slumber Version: 1.8.0

**Additional context**

**Comment by hans-strudle** [comment]
@LucasPickering saw your reddit post about this issue and took a look and I have gotten the same issue, also on mac myself. I'm just now learning rust but was able to get the keycodes from VIM logged and I seemed to get these keys over and over after editing in vim:
`
1;95;0c;
`
the last `c` would cause the TUI to jump to the Recipe panel, would occasionally get some other gibberish but this string happened all the time. 
Some googling suggested that its most likely due to vim plugins and maybe the `~/.vimrc`, so I modified the `EditorBuilder` command to add the args `--noplugin -u NONE`, which turns off plugins and tell vim to not use any .vimrc.

Example diff:
`
--- a/crates/slumber_tui/src/lib.rs
+++ b/crates/slumber_tui/src/lib.rs
@@ -420,3 +420,6 @@ impl Tui {
         })?;
-        command.status().context(error_context)?;
+        command
+            .args(["--noplugin", "-u", "NONE"])
+            .status()
+            .context(error_context)?;
         // If the editor was terminal-based it probably dropped us out of the
`
This gets rid of the issue for me, at the loss of my plugins and colorscheme etc, altho that should be acceptable for just a quick edit I hope. Haven't tested this deeply but wanted to share my findings with you, also super cool project I love it!

**Comment by LucasPickering** [comment]
@hans-strudle Thanks for finding this! I didn't even think to look at my `vimrc`, I set that up like 5 years ago and haven't thought about it since 😛. I'll have to do some deeper debugging and see what exactly in there is causing the issue.
