### ISSUE TITLE
Follow XDG Base Directory Specification for Linux

### ISSUE THREAD

**Issue by SVendittelli** [LucasPickering/slumber#371]
## Problem

On Linux, the database, log, and config files are all being stored in `$XDG_DATA_HOME` which doesn't follow the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/).

## Proposed solution

There is no issue with any of these files being stored in a `slumber` subdirectory of the following proposed locations.

The database file (`state.sqlite`) should be stored in the [`dirs::data_dir`](https://docs.rs/dirs/latest/dirs/fn.data_dir.html), as it currently is, no change needed.

The config file (`config.yml`) should be stored in [`dirs::config_dir`](https://docs.rs/dirs/latest/dirs/fn.config_dir.html). This points to the same location on macOS and Windows, so would be backwards compatible for those platforms, but would be different for Linux (i.e. `$XDG_CONFIG_HOME` not `$XDG_DATA_HOME`). _This would be a breaking change._

The log file (`slumber.log`) is more tricky. According to the spec, this should be stored in `$XDG_STATE_HOME` on Linux, provided by [`dirs::state_dir`](https://docs.rs/dirs/latest/dirs/fn.state_dir.html). However, this does not have Windows and macOS equivalents in the `dirs` crate. For Windows and macOS, the [`dirs::cache_dir`](https://docs.rs/dirs/latest/dirs/fn.cache_dir.html) would be an acceptable fallback. _This would be a breaking change._

## Additional context

1. [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/)
2. [`dirs` crate](https://docs.rs/dirs/latest/dirs/index.html)

**Comment by LucasPickering** [comment]
Thanks for the detailed report. To be honest, I didn't put a ton of thought into the directory locations, I just pulled in `dirs` and ran with it. I'm happy to make this change. I have no problem moving the log files without considering it a breaking change, because I don't think anyone has any level of automation or workflows built off the log files. In fact this is the first time anyone other than me has acknowledged their existence.

For the config change, to keep it backward compatible we can just continue to check the old location, but suggest the new location in documentation/command output.

**Comment by SVendittelli** [comment]
That all sounds great to me, thanks for considering it.
