### ISSUE TITLE
Allow code-folding of JSON response bodies

### ISSUE THREAD

**Issue by anussel5559** [LucasPickering/slumber#398]
**Did you [search](https://github.com/LucasPickering/slumber/issues) for existing issues already?**
yup!

**Is your feature request related to a problem? Please describe.**
Not an issue - purely a QoL enhancement

**Describe the solution you'd like**
Right now, it's pretty easy for a response body to overflow the length of the response pane in the main slumber view. Scrolling is easy as is filtering, but code folding might be a nice way for users to move about the response.

**Describe alternatives you've considered**
None outside of piping the result of a singular `slumber` request to something like [otree](https://github.com/fioncat/otree)

**Additional context**
Maybe there's a way to leverage otree inside the response pane? 🤷

**Comment by anussel5559** [comment]
maybe [tui-rs-tree-widget](https://github.com/EdJoPaTo/tui-rs-tree-widget)?

**Comment by LucasPickering** [comment]
I had originally looked into `tui-rs-tree-widget` when adding the tree view to the left Recipes pane. I decided not to use it because the amount of glue code required to make it work with Slumber's data structures was about the same complexity as just reimplementing it myself. We could reuse the tree code from that for a JSON explorer. In terms of a third party library, I was thinking of something more all-inclusive, where you just give it a `serde_json::Value` and it makes it all pretty and foldable for you. Probably doesn't exist though.

**Comment by LucasPickering** [comment]
I've decided not to build this into Slumber. Instead you can use an external pager to navigate bodies (see #404). Long term I'd like to find a way to embed external programs within the TUI to make that even easier.
