### ISSUE TITLE
Input Binding with shift modifier not working when trying to map a key that is mapped without the modifier

### ISSUE THREAD

**Issue by ttytm** [LucasPickering/slumber#401]
**Describe the bug**
_A clear and concise description of what the bug is_

The mapped action with the shift modifier below will not work

```yaml
input_bindings:
  home: [g]
  end: [shift g]
```

Same goes for other tested mappings. E.g. when mapping `[l]` to one and `[shift l]` to another action, the mapping with the modifier is not working.

**Version (please complete the following information):**

- OS: linux x64
- Terminal: kitty, wezterm, foot
- Slumber Version: 2.1

**Comment by LucasPickering** [comment]
Thanks for the report. Turns out that any key combination involving `shift` and a letter is broken, regardless of whether you have the letter itself bound. I'm about to merge a fix and will put out a release in the next few days. In the mean time though you should be able to get this working by changing the binding to `shift G`. That binding should continue to work after the fix too.

**Comment by ttytm** [comment]
Uff, weak observations on my side :see_no_evil: 

Thanks for looking into it, @LucasPickering! A really nice piece of software you provide with slumber. Already better than many bigger projects. An my goto :slightly_smiling_face:  Personally, I just miss two small features to call it perfect. They fit in with the current design decision and should blend in well with the existing features. I'll open feature requests for them when I have a free moment, if that's okay.

**Comment by LucasPickering** [comment]
@ttytm Yeah please do! Always looking for more feedback

**Comment by ttytm** [comment]
Thanks was already using it on `master`. Good work!
